# Generated by Django 4.2.23 on 2025-06-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='city',
            field=models.CharField(choices=[('Aleppo', 'Aleppo'), ('Damascus', 'Damascus'), ('Daraa', 'Daraa'), ('Deir Ezzor', 'Deir Ezzor'), ('Homs', 'Homs'), ('Latakia', 'Latakia'), ('Tartus', 'Tartus')], max_length=100, verbose_name='City'),
        ),
    ]
