# Generated by Django 4.2.23 on 2025-07-04 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='identity_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='The national ID must be exactly 10 digits long', regex='^[01]\\d{9}$')], verbose_name='National ID'),
        ),
    ]
