# Generated by Django 4.2.23 on 2025-06-29 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='Street Address')),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Neighborhood')),
                ('building_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Building Number')),
                ('city', models.CharField(choices=[('Damascus', 'Damascus'), ('Aleppo', 'Aleppo'), ('Homs', 'Homs'), ('Latakia', 'Latakia'), ('Tartus', 'Tartus'), ('Daraa', 'Daraa'), ('Deir Ezzor', 'Deir Ezzor')], max_length=100, verbose_name='City')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Description')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal Code')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userapplication', verbose_name='UserApplication')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ['user', 'city'],
            },
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Wallet',
                'verbose_name_plural': 'User Wallets',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Description')),
                ('price', models.FloatField(verbose_name='Price')),
                ('quantity_available', models.IntegerField(verbose_name='Quantity Available')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Product Image')),
                ('video_file', models.FileField(upload_to='videos/', verbose_name='Video File')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('condition', models.CharField(choices=[('Brand New', 'Brand New'), ('Like New', 'Like New'), ('Good Condition', 'Good Condition'), ('Fair Condition', 'Fair Condition'), ('Poor Condition', 'Poor Condition')], max_length=50, verbose_name='Product Condition')),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=20, verbose_name='Status')),
                ('id_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.address', verbose_name='Address')),
                ('id_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userapplication', verbose_name='Buyer')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=25, verbose_name='Subject')),
                ('message', models.CharField(max_length=1000, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userapplication', verbose_name='UserApplication')),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
            },
        ),
    ]
