# Generated by Django 4.2.23 on 2025-06-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_userwallet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not_Available', 'Not Available')], default='Available', max_length=20, verbose_name='Status'),
        ),
    ]
