# Generated by Django 4.2.23 on 2025-07-04 01:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_email'),
        ('services', '0003_alter_product_image_alter_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Time')),
                ('status', models.BooleanField(blank=True, default=None, help_text='Accepted/Rejected', null=True, verbose_name='Status Join Request')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.delivery', verbose_name='Delivery')),
            ],
            options={
                'verbose_name': 'Join Request',
                'verbose_name_plural': 'Join Requests',
                'ordering': ['date_time'],
            },
        ),
    ]
