# Generated by Django 4.2.23 on 2025-07-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_product_status_requestswap_requestbuying'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestbuying',
            options={'ordering': ['-created_at'], 'verbose_name': 'Request Buying', 'verbose_name_plural': 'Request Buyings'},
        ),
        migrations.AlterField(
            model_name='requestswap',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('No Payment Required', 'No Payment Required')], max_length=20, null=True, verbose_name='Payment Status'),
        ),
    ]
