# Generated by Django 4.2.23 on 2025-07-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_requestbuying_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbuying',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Wallet', 'Wallet')], help_text='Payment method must be either Cash or Wallet', max_length=20, null=True, verbose_name='Payment Method'),
        ),
    ]
