# Generated by Django 4.2.23 on 2025-07-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_requestbuying_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestswap',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Wallet', 'Wallet')], help_text='Set only if payment is required', max_length=20, verbose_name='Payment Method'),
        ),
    ]
