# Generated by Django 4.2.23 on 2025-07-11 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_requestswap_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestswap',
            name='product_offered',
        ),
        migrations.RemoveField(
            model_name='requestswap',
            name='product_requested',
        ),
        migrations.RemoveField(
            model_name='requestswap',
            name='requester',
        ),
        migrations.DeleteModel(
            name='RequestBuying',
        ),
        migrations.DeleteModel(
            name='RequestSwap',
        ),
    ]
