# Generated by Django 4.2.23 on 2025-07-11 19:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_delivery_identity_number'),
        ('services', '0010_remove_requestswap_product_offered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestSwap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20, verbose_name='Status')),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Wallet', 'Wallet')], help_text='Set only if payment is required', max_length=20, verbose_name='Payment Method')),
                ('payment_status', models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('No Payment Required', 'No Payment Required')], max_length=20, null=True, verbose_name='Payment Status')),
                ('delivery_type', models.CharField(choices=[('Hand Delivery', 'Hand Delivery'), ('Home Delivery', 'Home Delivery')], help_text='Specify if delivery is hand delivery or home delivery', max_length=20, verbose_name='Delivery Type')),
                ('id_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.address', verbose_name='Address')),
                ('product_offered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_offers', to='services.product', verbose_name='Product Offered')),
                ('product_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_received', to='services.product', verbose_name='Product Requested')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_made', to='user.userapplication', verbose_name='Requester')),
            ],
            options={
                'verbose_name': 'Request Swap',
                'verbose_name_plural': 'Request Swaps',
                'ordering': ['-created_at'],
            },
        ),
    ]
