# Generated by Django 4.2.23 on 2025-07-13 00:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_delivery_identity_number'),
        ('services', '0012_requestbuying'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(verbose_name='Total Amount')),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Preparing', 'Preparing'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='Pending', max_length=30, verbose_name='Order Status')),
                ('delivery_rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Delivery Rating (1-5)')),
                ('delivery_comment', models.TextField(blank=True, null=True, verbose_name='Delivery Comment')),
                ('seller_rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Seller Rating (1-5)')),
                ('seller_comment', models.TextField(blank=True, null=True, verbose_name='Seller Comment')),
                ('buyer_rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Buyer Rating (1-5)')),
                ('buyer_comment', models.TextField(blank=True, null=True, verbose_name='Buyer Comment')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('id_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_orders', to='user.delivery', verbose_name='Delivery Person')),
                ('swap_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='services.requestswap', verbose_name='Swap Request')),
            ],
            options={
                'verbose_name': 'Swap Order',
                'verbose_name_plural': 'Swap Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
