# Generated by Django 4.2.23 on 2025-07-13 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_delivery_identity_number'),
        ('services', '0014_swaporder_payer_of_difference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swaporder',
            name='payer_of_difference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_orders_paying', to='user.userapplication', verbose_name='Payer of Difference'),
        ),
    ]
