# Generated by Django 5.2.4 on 2025-07-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_remove_buyorder_buyer_delivery_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyorder',
            name='delivery_comment',
        ),
        migrations.RemoveField(
            model_name='buyorder',
            name='delivery_rating',
        ),
        migrations.RemoveField(
            model_name='swaporder',
            name='delivery_comment',
        ),
        migrations.RemoveField(
            model_name='swaporder',
            name='delivery_rating',
        ),
        migrations.AddField(
            model_name='buyorder',
            name='buyer_delivery_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Delivery Comment by Buyer'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='buyer_delivery_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Delivery Rating by Buyer (1-5)'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='seller_delivery_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Delivery Comment by Seller'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='seller_delivery_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Delivery Rating by Seller (1-5)'),
        ),
        migrations.AddField(
            model_name='swaporder',
            name='buyer_delivery_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Delivery Comment by Buyer'),
        ),
        migrations.AddField(
            model_name='swaporder',
            name='buyer_delivery_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Delivery Rating by Buyer (1-5)'),
        ),
        migrations.AddField(
            model_name='swaporder',
            name='seller_delivery_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Delivery Comment by Seller'),
        ),
        migrations.AddField(
            model_name='swaporder',
            name='seller_delivery_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Delivery Rating by Seller (1-5)'),
        ),
    ]
